### ISSUE TITLE
Errno 8: nodename nor servname provided, or not known.

### ISSUE THREAD

**Issue by nicdichiara** [NoxArt/SublimeText2-FTPSync#120]
Hello. I keep getting the above error. This is a direct copy-paste of my ftpsync.settings file:

{

```
"default": {

    "host": "ftp.mysite.com",
    "username": "myusername",  // or null for anonymous login
    "password": "mypassword",
    "path": "/",

    "upload_on_save": true 
    }
```

}

I know that doesn't give you much information because it's basically the default config...but that is also why I am curious to see errors. I know that my information is correct; I used the exact same values in Dreamweaver 10 minutes prior with no issues.

I have read though issue #41 which is of the same error. It was asked whether it was the first time being used. This is my first time using it and have not been able to successfully perform a ftp operation with ftpsync yet.

Additional Info: There are no subdirectories in this folder.

**Comment by klihelp** [comment]
Happening this issue on my side too, figuring out what it could be as ftp details works with Filezilla. Nice plugin!

**Comment by klihelp** [comment]
On my case worked as using IP address for the host.

**Comment by truebeck-datawh** [comment]
Using IP address as host worked for me too.
