### ISSUE TITLE
Add settings to manage default permissions for uploaded file

### ISSUE THREAD

**Issue by ridethepenguin** [NoxArt/SublimeText2-FTPSync#123]
When a local file is uploaded to a remote server for the first time, the permissions are by default 600.

I thought it would be nice to have a way to change this behavior, as one can do for newly created folders tweaking the "default_folder_permissions" setting.

For the time being, I simply added a line in ftpsyncwrapper.py to change permissions after a file is uploaded to what I deem a more reasonable default, i.e. 644.

Added this code after line 367 in ftpsyncwrapper.py:

```
self.chmod(path, "644");
```

If you give me some guidance, I may be able to implement this feature myself... I'm very new to Sublime Text.

**Comment by CrafterSama** [comment]
I don't know why, but this doesn't working on linux, specifically in ubuntu 17.04, always takes permissions 0600
