### ISSUE TITLE
Timezone difference sets wrong last-modified time on uploaded files

### ISSUE THREAD

**Issue by marcoflorian** [NoxArt/SublimeText2-FTPSync#143]
Hi again,

This plugin is pretty useful for me and I use it pretty much on the projects I work on :) Thank you!

I just found a thing I can't seem to fix it with the settings:

Server is with a timezone set to -5.
Local is with a timezone set to -5 too.

When a file is uploaded using the plugin the time 5 hours less than what it should be.

So, let's say right now it is 8 am. I have a file in the server which was last modified at 7:50 am. I do see the time through SSH, or using an FTP client. I modify this file using ST3 and the plugin uploads it automatically. Now, when I go back to check the file using SSH or the same FTP client, the last-modified time is set to 3 am.

I played around with the time_offset and set_remote_lastmodified settings but nothing.

Plugin bug or wrong settings? All I have in the settings is:

{
    "default": {
        "host": "...",
        "username": "...",
        "password": "...",
        "path": "/public_html/.../",
        "upload_on_save": true
    }
}

Thanks.

**Comment by jslot** [comment]
I'm experiencing the same thing here. FTP sync saves the file on the server 1 hour in the future. This is causing annoying popups if I wanna overwrite.
Running PureFTPD on a Debian system. Checked if my timezone and stuff was wrong on both server and local machine.

Here comes the interesting-
I'm currently working on an old template for a webpage if I edit a brand new file the problem does not appear.

**Comment by cvladan** [comment]
I am having the same issue.
`set_remote_lastmodified` is setting the wrong time.

I believe this is happening as according to the RFC the MDTM value shall be in UTC.
But for me, it's not working even if I set `time_offset`.

To solve this kind of issues, for example, Total Commander's client has additional setting `UTC` besides the `MDTM`. Maybe you can also add one?

**Comment by michfield** [comment]
Now I checked the competing non-free package Sublime SFTP from wbond.
They have an option to tackle this kind of issues. Directive is named `remote_locale`.

http://wbond.net/sublime_packages/sftp/settings#setting-remote_locale

**Comment by lechat69** [comment]
Same problem here. I think it's the UTC time which is sent to the server, and not the local time...

**Comment by Alecto** [comment]
i have the same problem.
and have not corrected a few years?

**Comment by carlosleonam** [comment]
I had the same problem too. Few months ago, i don't remeber where, but i found a solution. I use the lines below:
**"overwrite_newer_prevention": true,**
**"time_offset": 120, // [minutes] not [seconds]**
**"set_remote_lastmodified": false,**

My TimeZone is UTC/GMT -3 hours, then "time_offset" is  120 minutes.

I use **"overwrite_newer_prevention": true,** to warning me when overwriting some file. If you don't need this, set it to **false**.
