### ISSUE TITLE
Overwrite prevention bug

### ISSUE THREAD

**Issue by winfried-van-loon** [NoxArt/SublimeText2-FTPSync#144]
Hi,

When using `ctrl+s` with FTPSync, sometimes there's a notice that a newer file already exists at the server. A pop-up is displayed saying with the `Yes, overwrite newer` and `No - cancel upload` options. In the console, this is called `Overwrite protection`.

After this pop-up is displayed, the file used to be saved to the server upon clicking 'yes'.
However, after a recent update of FTPSync (we believe today) the file does not upload anymore.

Using the left sidebar, upon right clicking the file and choosing `upload`, the file does get uploaded correctly. The 'Overwrite prevention' pop-up is not displayed, which makes me think it has something to do with the pop-up. Or with the recently updated async saving update, #141.

I've got the console messages as well, although there doesn't seem to be any errors.

```
Writing file /C/Apache24/htdocs/project/app/controllers/file.php with encoding UTF-8 (atomic)
b'FTPSync [default] > Connected to: host:21 (timeout: 30) (key: 2d9c4583cbe5b27e8e3edcf8fdf8d622)'
b'FTPSync [default] > Logged in as: user (using password: YES)'
b'FTPSync > Closing connection'
b'FTPSync > Overwrite prevention: overwriting'
```

Thank you for your time.

**Comment by 0xfib** [comment]
Hi, I don't find the docs to disable the "Yes, overwrite newer" - " No". It's very annoying when I save the file to ask for permission to upload when exactly that I want to do.
