### ISSUE TITLE
How to do silent upload 

### ISSUE THREAD

**Issue by ozgrozer** [NoxArt/SublimeText2-FTPSync#184]
How to do silent upload when the file is saved?

**Comment by NoxArt** [comment]
What do you mean by *silent* upload?

**Comment by ozgrozer** [comment]
When I save the file, there is a prompt box for upload file or cancel it. How can I upload the file without promt box?

**Comment by NoxArt** [comment]
This happens when according the available data the remote file seems newer & different in size than the local file, so it warns about overwriting. If you wish to disable it, add this into config

    "overwrite_newer_prevention": true

**Comment by ozgrozer** [comment]
I already have these lines but still appears confirm box every cmd + s press. 

```
"upload_on_save": true,
"overwrite_newer_prevention": true,
```

**Comment by NoxArt** [comment]
Sorry, my bad, I meant **false**

**Comment by ozgrozer** [comment]
It worked :)
Thank you so much.

**Comment by NoxArt** [comment]
You're welcome

**Comment by ozgrozer** [comment]
Hello,

I have a new question.
How can I hide this confirm box?

![Sublime](http://i.imgur.com/gDEkAWP.png)

**Comment by NoxArt** [comment]
"download_on_open": false

feel free to look into https://github.com/NoxArt/SublimeText2-FTPSync/wiki/All-settings for all the available settings

**Comment by ozgrozer** [comment]
Ok thank you

**Comment by NoxArt** [comment]
Hi, it should be fixed now, sorry it took so long
