### ISSUE TITLE
Settings for specific files to download/upload

### ISSUE THREAD

**Issue by luizj** [NoxArt/SublimeText2-FTPSync#189]
Please, you can add a option for set specified files to sync down/up ?

I have 5gb in my ftp, i just need some files with *.php *.html *.css *.js

Thanks, excellent plugin!

**Comment by NoxArt** [comment]
Hi, I don't think this is overly used, but you can try setting up more connections in the settings file with `ignore` property ignoring everything but the files with the specific extension ... be sure to specify the regular well enough, there's also wiki:

https://github.com/NoxArt/SublimeText2-FTPSync/wiki/Ignore-settings-option-described

http://www.regular-expressions.info

https://regex101.com

**Comment by luizj** [comment]
Ok, solved, thanks for fast reply.

I'm added this:
"ignore": "ftpsync\\.settings|\\.gitignore|\\.git|Sublime Text 2/Packages|\\.exe|\\.jpg|\\.ico|\\.png|\\.gif|\\.swf|\\.fla|\\.rar|\\.zip|\\.pdf"
