### ISSUE TITLE
there is one mistake in "All settings"

### ISSUE THREAD

**Issue by dalianwa** [NoxArt/SublimeText2-FTPSync#190]
from   https://github.com/NoxArt/SublimeText2-FTPSync/wiki/All-settings
at "debug settings"

 print_list_result: bool
"print_list_results": true,

if print_list_result eq print_list_results  ?

**Comment by NoxArt** [comment]
Hi, sorry for such a late response. Good catch, it's without "s", fixed it
Thank you!
