### ISSUE TITLE
Failed Parsing Conf File

### ISSUE THREAD

**Issue by astonmatn** [NoxArt/SublimeText2-FTPSync#192]
Hi,

i get an error while saving the FTP Plugin in  ST3.
What are I am doing wrong?

*NoxArt: removed screenshot*

Thank you

aston

**Comment by fabuio** [comment]
line 20: remove comma
"overwrite_newer_prevention": true

**Comment by thecotne** [comment]
@fabuio actually extra commas are allowed see #176 

@astonmatn you have escaped closing quote at line 9 with backslash

**Comment by astonmatn** [comment]
@thecotne Merci, that's the resolution of my problem!!!

**Comment by NoxArt** [comment]
Thank you guys for jumping in! I just took a liberty of removing the screenshot since it **contained password** (although the value of the password could theoretically break the syntax too, if it contained ", it's still better to avoid it initially)
