### ISSUE TITLE
Replace code for multiple servers

### ISSUE THREAD

**Issue by angeljunior** [NoxArt/SublimeText2-FTPSync#205]
It's possible replace my code, for upload, in multiples servers?

**Comment by NoxArt** [comment]
Hi,
not sure I understand 100 %, but if you want to upload to more servers at once, simply add another setting entry in your ftpsync.settings as seen in
https://github.com/NoxArt/SublimeText2-FTPSync/wiki/All-settings

for example

    {
        "firstServer: {
            "host": "...",
            "username": "...",
            "password": "...",
            "path": "...",

            "debug_extras": {
                "print_list_result": true,
                "debug_mfmt": true
            }
        },
        "secondServer: {
            "host": "...",
            "username": "...",
            "password": "...",
            "path": "...",

            "debug_extras": {
                "print_list_result": true,
                "debug_mfmt": true
            }
        }
    }

thirdServer (or whatever name you choose) and so on

Does this help?
