### ISSUE TITLE
no instructions on how to access ftps stored in config

### ISSUE THREAD

**Issue by sommerper** [NoxArt/SublimeText2-FTPSync#223]
how do i actually use this?

**Comment by NoxArt** [comment]
Hi,
there is a description in the Readme / index page of this repo.
https://github.com/NoxArt/SublimeText2-FTPSync

Also there are Wiki entries
https://github.com/NoxArt/SublimeText2-FTPSync/wiki

In Sublime, you can find individual actions and commands in:
* Current file's context menu
* Sidebar's context menu
* Command pallete
* Preferences > Key bindings

As for the most basic functionality:
If the connection is setup, saving the file is uploaded on saving the file (unless this is disabled).
To browse the FTP choose Browse from current file's context menu or command pallete.

Hope this clears it up

**Comment by sommerper** [comment]
Thanks! I completely missed that. I'd like to suggest that you put a small notice in the main readme either pointing to the wiki page or even a copy/paste from there to get started quickly.
