### ISSUE TITLE
Exception: Expecting value Line 1 Col 1

### ISSUE THREAD

**Issue by devWaleed** [NoxArt/SublimeText2-FTPSync#231]
```
{
	"primary": {
	    "host": "ftp.mywebsite.com",
	    "username": "johnsmith",
	    "password": "secretpassword",
	    "path": "/www/",
	    "upload_on_save": true,
	    "tls": true
	}
}
```

FFS! What is wrong here -_- ? Someone please fix the wiki, its not even a proper JSON syntax, how can you put it up in the README file? -_- Line 1 Col 1 is that first starting { what's wrong here?

**Comment by ImSeaWorld** [comment]
According to http://jsonlint.com/ it's valid JSON.

**Comment by OscarEriksen** [comment]
Same issue. Maintainer, please fix this.

**Comment by NoxArt** [comment]
Hi,
the example is valid, I've found out that when this happens the content read is actually empty, hence the complaint about first character.

Unfortunately there never been any clear-cut "steps to reproduce" (it always worked on my end, multiple machines), so I'm working rather blind so far. I have added some checks and retry mechanism, hopefully it helps. If not, please try to enable debugJson in the global settings (accessible from Menu > Preferences > Package Settings)
Thank you
