### ISSUE TITLE
How to upload files to multiple servers?

### ISSUE THREAD

**Issue by xBioClown** [NoxArt/SublimeText2-FTPSync#232]
Hello there,
My case is that i have 2 server for the policies of my employer, how ever we have the first server that is the main and the second in case the first one fail, is there a way to upload any changes in my local files to 2 o more servers?

Thanks for giving some help.

**Comment by NoxArt** [comment]
Hi,
just add another configuration, see https://github.com/NoxArt/SublimeText2-FTPSync/blob/master/README.md at the bottom

Basically copy the "default" part (all within the main { brackets } ) separating them by comma, and replace the second "default" name with something else ... the first one doesn't need to be called "default" either, you can name it however you like. 
However for downloads the first connections is treated as default.
