### ISSUE TITLE
Can't download hidden file (.gitignore and .git )

### ISSUE THREAD

**Issue by windard** [NoxArt/SublimeText2-FTPSync#247]
I use sublime 2 in Windows 10 , connect to Cent OS 7 via vsftpd. 
Everything is perfect,but when I init a git repository in Cent OS,and prepare to download file to local directory, `.git` and `.gitignore` aren't downloaded.

**Comment by NoxArt** [comment]
Hi, either modify default global setting (easier, non-persistent) or user-settings (recommended) of FTPSync, modify the original "ignore" property https://github.com/NoxArt/SublimeText2-FTPSync/blob/master/FTPSync.sublime-settings#L67

    {
        "ignore": "ftpsync\\.settings"
    }

**Comment by windard** [comment]
Thank you
